import type { AssetCatalogue, AssetDescriptor } from "./AssetDescriptor";

const asset = (descriptor: AssetDescriptor): AssetDescriptor => descriptor;

export const STARTER_ASSET_CATALOGUE: AssetCatalogue = {
  assets: [
    asset({
      key: "environment-starter-market-base",
      path: "assets/game/environments/stores/starter-market/base.webp",
      category: "environment",
      canvasSize: [1600, 900],
      anchor: [0, 0],
      defaultScale: 1,
      depthGroup: "far-environment",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "base",
      status: "concept"
    }),
    asset({
      key: "fixture-produce-display-a",
      path: "assets/game/fixtures/produce-displays/produce-display-a.webp",
      category: "fixture",
      canvasSize: [620, 700],
      anchor: [0.5, 0.92],
      defaultScale: 1,
      depthGroup: "fixtures",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "stocked",
      status: "concept"
    }),
    asset({
      key: "fixture-backroom-rack-a",
      path: "assets/game/fixtures/backroom-racks/backroom-rack-a.webp",
      category: "fixture",
      canvasSize: [540, 580],
      anchor: [0.5, 0.92],
      defaultScale: 1,
      depthGroup: "fixtures",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "stocked",
      status: "concept"
    }),
    asset({
      key: "fixture-beverage-cooler-a",
      path: "assets/game/fixtures/coolers/beverage-cooler-a/base.webp",
      category: "fixture",
      canvasSize: [680, 820],
      anchor: [0.5, 0.92],
      defaultScale: 1,
      depthGroup: "fixtures",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "base",
      status: "concept"
    }),
    ...Array.from({ length: 6 }, (_, index): AssetDescriptor => ({
      key: `fixture-beverage-cooler-a-row-${String(index + 1).padStart(2, "0")}`,
      path: `assets/game/fixtures/coolers/beverage-cooler-a/row-${String(index + 1).padStart(2, "0")}.png`,
      category: "product",
      canvasSize: [520, 90],
      anchor: [0.5, 0.5],
      defaultScale: 1,
      depthGroup: "fixture-contents",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: `stock-row-${index + 1}`,
      status: "concept"
    })),
    asset({
      key: "worker-a-idle",
      path: "assets/game/characters/workers/worker-a/idle.webp",
      category: "character",
      canvasSize: [700, 1000],
      anchor: [0.5, 0.94],
      defaultScale: 0.42,
      depthGroup: "actors",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "idle",
      status: "concept"
    }),
    asset({
      key: "worker-a-carry-medium",
      path: "assets/game/characters/workers/worker-a/carry-medium.webp",
      category: "character",
      canvasSize: [700, 1000],
      anchor: [0.5, 0.94],
      defaultScale: 0.42,
      depthGroup: "actors",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "carry-medium",
      status: "concept"
    }),
    asset({
      key: "worker-a-push-cart",
      path: "assets/game/characters/workers/worker-a/push-cart.webp",
      category: "character",
      canvasSize: [760, 1040],
      anchor: [0.5, 0.94],
      defaultScale: 0.42,
      depthGroup: "actors",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "push-cart",
      status: "concept"
    }),
    asset({
      key: "worker-a-open-case",
      path: "assets/game/characters/workers/worker-a/open-case.webp",
      category: "character",
      canvasSize: [760, 1040],
      anchor: [0.5, 0.94],
      defaultScale: 0.42,
      depthGroup: "actors",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "open-case",
      status: "concept"
    }),
    ...(["place-low", "place-middle", "place-high"] as const).map((state): AssetDescriptor => ({
      key: `worker-a-${state}`,
      path: `assets/game/characters/workers/worker-a/${state}.webp`,
      category: "character",
      canvasSize: [760, 1040],
      anchor: [0.5, 0.94],
      defaultScale: 0.42,
      depthGroup: "actors",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state,
      status: "concept"
    })),
    asset({
      key: "equipment-restock-cart-empty",
      path: "assets/game/equipment/restock-carts/cart-a-empty.png",
      category: "equipment",
      canvasSize: [520, 620],
      anchor: [0.5, 0.91],
      defaultScale: 0.44,
      depthGroup: "props",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "empty",
      status: "concept"
    }),
    asset({
      key: "equipment-restock-cart-loaded",
      path: "assets/game/equipment/restock-carts/cart-a-loaded.png",
      category: "equipment",
      canvasSize: [520, 620],
      anchor: [0.5, 0.91],
      defaultScale: 0.44,
      depthGroup: "props",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "loaded",
      status: "concept"
    }),
    asset({
      key: "prop-cola-case-closed",
      path: "assets/game/props/cases/cola-case-closed.png",
      category: "prop",
      canvasSize: [360, 260],
      anchor: [0.5, 0.86],
      defaultScale: 0.42,
      depthGroup: "props",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "closed",
      status: "concept"
    }),
    asset({
      key: "prop-cola-case-open",
      path: "assets/game/props/cases/cola-case-open.png",
      category: "prop",
      canvasSize: [400, 300],
      anchor: [0.5, 0.86],
      defaultScale: 0.42,
      depthGroup: "props",
      preloadGroup: "starter-market",
      perspective: "fixed-third-person",
      lightDirection: "upper-left",
      state: "open",
      status: "concept"
    }),
    asset({
      key: "effect-active-target-arrow",
      path: "assets/game/effects/arrows/active-target.svg",
      category: "effect",
      canvasSize: [128, 160],
      anchor: [0.5, 1],
      defaultScale: 1,
      depthGroup: "world-effects",
      preloadGroup: "core-ui",
      perspective: "screen-space",
      state: "active",
      status: "concept"
    }),
    asset({
      key: "ui-hud-task-panel",
      path: "assets/game/ui/panels/task-panel.svg",
      category: "ui",
      canvasSize: [440, 170],
      anchor: [1, 0],
      defaultScale: 1,
      depthGroup: "ui",
      preloadGroup: "core-ui",
      perspective: "screen-space",
      state: "default",
      status: "concept"
    })
  ]
};
